# Generated by Django 5.0.6 on 2024-06-03 00:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='Reguser',
        ),
    ]
