# Generated by Django 5.0.6 on 2024-06-03 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_alter_user_table'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='User',
            new_name='Reguser',
        ),
    ]
